routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(
[
	'prefix' => 'admin',
	'as'=>'admin.',
	'middleware' => [
		'role:admin,superadmin,editor',
	]
], function() {

   	Route::get('dashboard', 'Admin\PageController@dashboard')->name('dashboard');
   	Route::get('/', 'Admin\PageController@dashboard')->name('index');

   	Route::resources([
    'users' => 'Admin\UserController',
	]);
	Route::get('users/{id}/active', 'Admin\UserController@active')->name('users.active');

	Route::resources([
    'roles' => 'Admin\RoleController',
	]);
	Route::resources([
    'permissions' => 'Admin\PermissionController',
	]);

});

app/Permission.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Permission extends Model
{
    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
	public function roles() {
		return $this->belongsToMany(Role::class,'roles_permissions');
    }

    public function users() {
		return $this->belongsToMany(User::class,'users_roles');
	}
}

app/Http/Controllers/Admin/PermissionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\PermissionRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use App\Permission;
use Toastr;

class PermissionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $permissions = Permission::paginate(10);
        return view('admin.pages.permissions.index',compact('permissions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permission = new Permission();
        return view('admin.pages.permissions.form', compact('permission'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PermissionRequest $request)
    {

        $permission = new Permission();
        $permission->slug = Str::slug($request->slug);
        $permission->name = $request->name;
        $permission->description = $request->description;

        $permission->save();

        Toastr::success('La permission a été crée avec succès !');

        return redirect()->route('admin.permissions.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $permission = Permission::find($id);

        if(!$permission){
            Toastr::error('Cette permission n\'existe pas ou a été supprimée');
            return redirect()->route('admin.permissions.index');
        }
        return view('admin.pages.permissions.form', compact('permission'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rules = [
            'slug' => 'required|string|max:255|unique:permissions,slug,'.$id,
            'name' => 'required|string|max:255',
            'description' => 'string',
        ];
        $request->validate($rules);

        $permission = Permission::find($id);
        if(!$permission){
            Toastr::error('Cette permission n\'existe pas ou a été supprimée');
            return redirect()->route('admin.permissions.index');
        }

        $permission->slug = Str::slug($request->slug);
        $permission->name = $request->name;
        $permission->description = $request->description;

        $permission->save();

        Toastr::success('La permission a été modifiée avec succès !');

        return redirect()->route('admin.permissions.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->middleware('role:superadmin');

        $permission = Permission::find($id);
        if(!$permission->delete()){
            Toastr::error('Une erreur s\'est produite lors de la suppression de la permission');
        }
        else{
            Toastr::success('Cette permission a été supprimée avec succès !');
        }

        return redirect()->route('admin.permissions.index');
    }
}

resources/views/admin/pages/permissions/form.blade.php
@extends('admin.layouts.base')

@section('title','Création d\'une permission')

@section('content')
<!-- Header -->
<div class="header bg-gradient-primary pb-8 pt-5 pt-md-8">
  <div class="container-fluid">
    <div class="header-body">
    </div>
  </div>
</div>
<div class="container mt--8 pb-5">
  <!-- Table -->
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8">
      <div class="card bg-secondary shadow border-0">
        <div class="card-body px-lg-5 py-lg-5">
          <div class="text-center text-muted mb-4">
            <small>Création d'une permission</small>
          </div>
          <form role="form" action="{{ ($permission->id) ? route('admin.permissions.update', $permission) : route('admin.permissions.store') }}" method="POST">
            @csrf
            @if($permission->id)
            <input type="hidden" name="_method" value="PUT">
            @endif
            <div class="form-group @if($errors->first('slug')) has-danger @endif">
              <label for="description">Slug</label>
              <div class="input-group input-group-alternative mb-3">
                <input class="form-control  
                @if($errors->first('slug')) is-invalid @endif" name="slug" value="{{ old('slug') ?? $permission->slug }}" placeholder="Slug de la permission" type="text">
              </div>
              @error('slug')
              <div class="invalid-feedback">
                {{ $message }}
              </div>
              @enderror
            </div>
            <div class="form-group @if($errors->first('name')) has-danger @endif">
              <label for="description">Nom</label>
              <div class="input-group input-group-alternative mb-3">
                <input class="form-control @if($errors->first('name')) is-invalid @endif" name="name" value="{{ old('name') ?? $permission->name }}" placeholder="Nom de la permission" type="text">
              </div>
              @error('name')
              <div class="invalid-feedback">
                {{ $message }}
              </div>
              @enderror
            </div>
            <div class="form-group @if($errors->first('description')) has-danger @endif">
              <label for="description">Description</label>
              <textarea class="form-control form-control-alternative @if($errors->first('description')) is-invalid @endif" rows="3" placeholder="Ecrivez quelque chose ici ..." name="description" id="description">{{ old('description') ?? $permission->description }}</textarea>
              @error('description')
              <div class="invalid-feedback">
                {{ $message }}
              </div>
              @enderror
            </div>
            <div class="text-center">
              <button type="submit" class="btn btn-primary mt-4">Ajouter une permission</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

@section('script')
<script type="text/javascript">
  $(document).ready(funection(){
  });
</script>
@endsection

resources/views/admin/pages/permissions/index.blade.php
@extends('admin.layouts.base')

@section('title','Gestion des permissions')

@section('content')
<!-- Header -->
<div class="header bg-gradient-primary pb-8 pt-5 pt-md-8">
  <div class="container-fluid">
    <div class="header-body">
    </div>
  </div>
</div>
<div class="container-fluid mt--7">
  <!-- Table -->
  <div class="row">
    <div class="col">
      <div class="card shadow">
        <div class="card-header border-0">
          <div class="row">
            <div class="col-sm-6">
              <h3 class="mb-0" style="padding: 0.625rem 0;">Liste des permissions</h3>
            </div>
            <div class="col-sm-6 text-right">
              <a href="{{ route('admin.permissions.create') }}" class="btn btn-primary"><i class="fas fa-user-plus"></i> Ajouter une permission</a>
            </div>
          </div>
        </div>
        <div class="table-responsive">
          <table class="table align-items-center table-flush">
            <thead class="thead-light">
              <tr>
                <th scope="col">Slug</th>
                <th scope="col">Nom</th>
                <th scope="col">Description</th>
                <th scope="col"></th>
              </tr>
            </thead>
            <tbody>
              @foreach($permissions as $permission)
              <tr>
                <th scope="row">
                  <span class="badge badge-default">{{ $permission->slug }}</span>
                </th>
                <td>
                  {{ $permission->name }}
                </td>
                <td>
                  {{ $permission->description }}
                </td>
                <td class="text-right">
                  <div class="dropdown">
                    <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-ellipsis-v"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                      <a class="dropdown-item" href="{{ route('admin.permissions.edit', $permission) }}"><i class="fas fa-pencil-alt text-blue"></i> Modifier</a>
                      @role('superadmin')
                      <a class="dropdown-item delete-item" href="{{ route('admin.permissions.destroy', $permission) }}" data-name="{{ $permission->name }}" data-id="{{ $permission->id }}" data-toggle="modal" data-target="#deleteModal"><i class="fas fa-trash text-red"></i> Supprimer</a>
                      @endrole
                    </div>
                  </div>
                </td>
              </tr>
              @endforeach
            </tbody>
          </table>
        </div>
        <div class="card-footer py-4">
            {{ $permissions->links() }}
        </div>
      </div>
    </div>
  </div>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Confirmation de suppression</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Vous êtes sur le point de supprimer la permission <span class="badge badge-info"></span> dans la base de données. Etes-vous sûr de cela ?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
          <form action="" method="POST">
            <input type="hidden" name="_method" value="DELETE">
            @csrf
            <button type="submit" class="btn btn-danger">Oui</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

@section('script')
<script type="text/javascript">
  $(document).ready(function(){

    var permissionName;
    var deleteUrl;

    $('a.delete-item').click(function(e) {
      deleteUrl = $(this).attr('href');
      permissionName = $(this).attr('data-name');
      e.preventDefault();
    });

    $('#deleteModal').on('show.bs.modal', function (e) {
      $(this).find('.modal-body .badge').text(permissionName);
      $(this).find('.modal-footer form').attr('action', deleteUrl);
    });

  });
</script>
@endsection