routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(
[
	'prefix' => 'admin',
	'as'=>'admin.',
	'middleware' => [
		'role:admin,superadmin,editor',
	]
], function() {

   	Route::get('dashboard', 'Admin\PageController@dashboard')->name('dashboard');
   	Route::get('/', 'Admin\PageController@dashboard')->name('index');

   	Route::resources([
    'users' => 'Admin\UserController',
	]);
	Route::get('users/{id}/active', 'Admin\UserController@active')->name('users.active');

	Route::resources([
    'roles' => 'Admin\RoleController',
	]);
	Route::resources([
    'permissions' => 'Admin\PermissionController',
	]);

});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Traits\HasPermissionsTrait;
use Laravel\Passport\HasApiTokens;

use Illuminate\Database\Eloquent\SoftDeletes;
use Kodeine\Metable\Metable;

class User extends Authenticatable
{
    use Notifiable, HasPermissionsTrait, HasApiTokens;

    use Metable;

    use SoftDeletes;

    protected $metaTable = 'users_meta';

    protected $dates = [
        'deleted_at',
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function posts()
    {
        return $this->hasMany(Post::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\UserRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use App\User;
use App\Role;
use Toastr;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::withTrashed()->paginate(10);
        return view('admin.pages.users.index',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = new User();
        $roles = Role::all();
        return view('admin.pages.users.form', compact('user','roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request)
    {

        $role = Role::find($request->role);
        $permissions = $role->permissions;

        $user = new User();
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = Hash::make($request->password);

        $user->save();

        $user->roles()->attach($role);
        foreach ($permissions as $permission) {
            $user->permissions()->attach($permission);
        }

        Toastr::success('L\'utilisateur a été crée avec succès !');

        return redirect()->route('admin.users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        $roles = Role::all();
        if(!$user){
            Toastr::error('Cet utilisateur n\'existe pas ou a été supprimé');
            return redirect()->route('admin.users.index');
        }
        return view('admin.pages.users.form', compact('user','roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rules = [
            'name' => 'required|string|max:255',
            'username' => 'required|string|min:6|max:255|unique:users,username,'.$id,
            'email' => 'required|string|email|max:255|unique:users,email,'.$id,
            'role' => 'required|exists:roles,id',
            ];
        if($request->password){
            $rules['password'] = 'required|string|min:8|confirmed';
        }

        $request->validate($rules);

        $user = User::find($id);

        $user->name = $request->name;
        $user->email = $request->email;
        if($request->password){
            $user->password = Hash::make($request->password);
        }

        $user->save();

        $role = Role::find($request->role);
        $permissions = $role->permissions;

        $user->permissions()->detach();
        $user->roles()->detach();

        $user->roles()->attach($role);

        foreach ($permissions as $permission) {
            $user->permissions()->attach($permission);
        }

        Toastr::success('L\'utilisateur a été modifié avec succès !');

        return redirect()->route('admin.users.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->middleware('role:superadmin');

        $user = User::find($id);
        
        Toastr::success('Cet utilisateur a été supprimé avec succès !');

        if(!$user->delete()){
            Toastr::error('Une erreur s\'est produite lors de la suppression de cet utilisateur');
        }

        return redirect()->route('admin.users.index');
    }

    public function active($id){
        $this->middleware('role:superadmin');

        $user = User::withTrashed()->where('id', $id)->first();

        if(!$user->restore()){
            Toastr::error('Une erreur s\'est produite lors de la réactivation de cet utilisateur');
        }
        else{
            Toastr::success('Cet utilisateur a été réactivé avec succès !');
        }

        return redirect()->route('admin.users.index');
    }
}

resources/views/admin/pages/users/form.blade.php
@extends('admin.layouts.base')

@section('title','Création des utilisateurs')

@section('content')
<!-- Header -->
<div class="header bg-gradient-primary pb-8 pt-5 pt-md-8">
  <div class="container-fluid">
    <div class="header-body">
    </div>
  </div>
</div>
<div class="container mt--8 pb-5">
  <!-- Table -->
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8">
      <div class="card bg-secondary shadow border-0">
        <div class="card-body px-lg-5 py-lg-5">
          <div class="text-center text-muted mb-4">
            <small>Création d'utilisateur</small>
          </div>
          <form role="form" action="{{ ($user->id) ? route('admin.users.update', $user) : route('admin.users.store') }}" method="POST">
            @csrf
            @if($user->id)
            <input type="hidden" name="_method" value="PUT">
            @endif
            <div class="form-group @if($errors->first('name')) has-danger @endif">
              <div class="input-group input-group-alternative mb-3">
                <div class="input-group-prepend">
                  <span class="input-group-text"><i class="ni ni-hat-3"></i></span>
                </div>
                <input class="form-control  
                @if($errors->first('name')) is-invalid @endif" name="name" value="{{ old('name') ?? $user->name }}" placeholder="Nom" type="text">
              </div>
              @error('name')
              <div class="invalid-feedback">
                {{ $message }}
              </div>
              @enderror
            </div>
            <div class="form-group @if($errors->first('username')) has-danger @endif">
              <div class="input-group input-group-alternative mb-3">
                <div class="input-group-prepend">
                  <span class="input-group-text"><i class="ni ni-hat-3"></i></span>
                </div>
                <input class="form-control  
                @if($errors->first('username')) is-invalid @endif" name="username" value="{{ old('username') ?? $user->username }}" placeholder="Nom d'utilisateur" type="text">
              </div>
              @error('username')
              <div class="invalid-feedback">
                {{ $message }}
              </div>
              @enderror
            </div>
            <div class="form-group @if($errors->first('email')) has-danger @endif">
              <div class="input-group input-group-alternative mb-3">
                <div class="input-group-prepend">
                  <span class="input-group-text"><i class="ni ni-email-83"></i></span>
                </div>
                <input class="form-control @if($errors->first('email')) is-invalid @endif" name="email" value="{{ old('email') ?? $user->email }}" placeholder="Email" type="email">
              </div>
              @error('email')
              <div class="invalid-feedback">
                {{ $message }}
              </div>
              @enderror
            </div>
            <div class="form-group">
              <label for="role">Rôle de l'utilisateur</label>
              <select id="role" class="form-control" name="role">
                @foreach($roles as $role)
                <option class="@if($errors->first('role')) is-invalid @endif" value="{{ $role->id }}" @if($user->hasRole($role->slug))selected="selected"@endif>{{ $role->name }}</option>
                @endforeach
              </select>
              @error('role')
              <div class="invalid-feedback">
                {{ $message }}
              </div>
              @enderror
            </div>
            <div class="form-group @if($errors->first('password')) has-danger @endif">
              <div class="input-group input-group-alternative">
                <div class="input-group-prepend">
                  <span class="input-group-text"><i class="ni ni-lock-circle-open"></i></span>
                </div>
                <input class="form-control @if($errors->first('password')) is-invalid @endif" name="password" placeholder="Mot de passe" type="password">
              </div>
              @error('password')
              <div class="invalid-feedback">
                {{ $message }}
              </div>
              @enderror
            </div>
            <div class="form-group @if($errors->first('password_confirmation')) has-danger @endif">
              <div class="input-group input-group-alternative">
                <div class="input-group-prepend">
                  <span class="input-group-text"><i class="ni ni-lock-circle-open"></i></span>
                </div>
                <input class="form-control @if($errors->first('password_confirmation')) is-invalid @endif" name="password_confirmation" placeholder="Retaper le mot de passe" type="password">
              </div>
              @error('password_confirmation')
              <div class="invalid-feedback">
                {{ $message }}
              </div>
              @enderror
            </div>
            <div class="text-center">
              <button type="submit" class="btn btn-primary mt-4">Ajouter un utilisateur</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

@section('script')
<script type="text/javascript">
  $(document).ready(function(){
  });
</script>
@endsection

resources/views/admin/pages/users/index.blade.php
@extends('admin.layouts.base')

@section('title','Gestion des utilisateurs')

@section('content')
<!-- Header -->
<div class="header bg-gradient-primary pb-8 pt-5 pt-md-8">
  <div class="container-fluid">
    <div class="header-body">
    </div>
  </div>
</div>
<div class="container-fluid mt--7">
  <!-- Table -->
  <div class="row">
    <div class="col">
      <div class="card shadow">
        <div class="card-header border-0">
          <div class="row">
            <div class="col-sm-6">
              <h3 class="mb-0" style="padding: 0.625rem 0;">Liste des utilisateurs</h3>
            </div>
            <div class="col-sm-6 text-right">
              <a href="{{ route('admin.users.create') }}" class="btn btn-primary"><i class="fas fa-user-plus"></i> Ajouter un utilisateur</a>
            </div>
          </div>
        </div>
        <div class="table-responsive">
          <table class="table align-items-center table-flush">
            <thead class="thead-light">
              <tr>
                <th scope="col">Utilisateur</th>
                <th scope="col">Roles</th>
                <th scope="col">Permissions</th>
                <th scope="col"></th>
              </tr>
            </thead>
            <tbody>
              @foreach($users as $user)
              <tr>
                <th scope="row">
                  <div class="media align-items-center">
                    <a href="#" class="avatar rounded-circle mr-3">
                      <img alt="Image placeholder" src="{{ asset('assets/admin/img/icons') }}/{{ $user->getMeta('picture') ?? 'user.png' }}">
                    </a>
                    <div class="media-body @if($user->trashed())token deleted @endif">
                      <span class="mb-0 text-sm">{{ $user->name }}</span>
                    </div>
                  </div>
                </th>
                <td>
                  @if($user->hasRole('superadmin'))
                  <span class="badge badge-danger @if($user->trashed())token deleted @endif">Super Administrateur</span>
                  @endif
                  @if($user->hasRole('admin'))
                  <span class="badge badge-success @if($user->trashed())token deleted @endif">Administrateur</span>
                  @endif
                  @if($user->hasRole('editor'))
                  <span class="badge badge-primary @if($user->trashed())token deleted @endif">Editeur</span>
                  @endif
                  @if($user->hasRole('user'))
                  <span class="badge badge-default @if($user->trashed())token deleted @endif">Utilisateur</span>
                  @endif
                </td>
                <td>
                  @forelse($user->permissions as $permission)
                    <span class="badge badge-info @if($user->trashed())token deleted @endif">{{ $permission->slug }}</span>
                  @empty
                    <span class="badge badge-info @if($user->trashed())token deleted @endif">Aucune permission particulière</span>
                  @endforelse
                </td>
                <td class="text-right">
                  <div class="dropdown">
                    <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-ellipsis-v"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                      @if($user->trashed())
                        @role('superadmin')
                        <a class="dropdown-item" href="{{ route('admin.users.active', $user) }}"><i class="fas fa-check text-green"></i> Réactiver</a>
                        @endrole
                      @else
                        <a class="dropdown-item" href="{{ route('admin.users.edit', $user) }}"><i class="fas fa-pencil-alt text-blue"></i> Modifier</a>
                        @role('superadmin')
                        <a class="dropdown-item delete-item" href="{{ route('admin.users.destroy', $user) }}" data-name="{{ $user->name }}" data-id="{{ $user->id }}" data-toggle="modal" data-target="#deleteModal"><i class="fas fa-trash text-red"></i> Supprimer</a>
                        @endrole
                      @endif
                    </div>
                  </div>
                </td>
              </tr>
              @endforeach
            </tbody>
          </table>
        </div>
        <div class="card-footer py-4">
            {{ $users->links() }}
        </div>
      </div>
    </div>
  </div>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Confirmation de suppression</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Vous êtes sur le point de supprimer l'utilisateur <span class="badge badge-info"></span> dans la base de données. Etes-vous sûr de cela ?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
          <form action="" method="POST">
            <input type="hidden" name="_method" value="DELETE">
            @csrf
            <button type="submit" class="btn btn-danger">Oui</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

@section('script')
<script type="text/javascript">
  $(document).ready(function(){

    var userName;
    var deleteUrl;

    $('a.delete-item').click(function(e) {
      deleteUrl = $(this).attr('href');
      userName = $(this).attr('data-name');
      e.preventDefault();
    });

    $('#deleteModal').on('show.bs.modal', function (e) {
      $(this).find('.modal-body .badge').text(userName);
      $(this).find('.modal-footer form').attr('action', deleteUrl);
    });

  });
</script>
@endsection